Created by:-

*   Vaibhav Chitransh
*   Id:-2022UME1836




Prediction of Diabetes by implementing different Models

*   Linear Regression
*   KNN Algorithm




In [1]:
# Importing libraries
import numpy as np
import pandas as pd
import matplotlib as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import r2_score, accuracy_score, confusion_matrix

In [4]:
# Importing diabetes csv file
df=pd.read_csv("/content/diabetes.csv")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 573 entries, 0 to 572
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Glucose                   573 non-null    int64  
 1   BloodPressure             561 non-null    float64
 2   BMI                       570 non-null    float64
 3   DiabetesPedigreeFunction  573 non-null    float64
 4   Age                       573 non-null    int64  
 5   Outcome                   573 non-null    int64  
dtypes: float64(3), int64(3)
memory usage: 27.0 KB


In [6]:
df.shape

(573, 6)

In [7]:
df.head()

Glucose  BloodPressure   BMI  DiabetesPedigreeFunction  Age  Outcome
0       89           66.0  28.1                     0.167   21        0
1      137           40.0  43.1                     2.288   33        1
2       78           50.0  31.0                     0.248   26        1
3      197           70.0  30.5                     0.158   53        1
4      110           92.0  37.6                     0.191   30        0

In [8]:
df.isnull().sum()

Glucose                      0
BloodPressure               12
BMI                          3
DiabetesPedigreeFunction     0
Age                          0
Outcome                      0
dtype: int64

In [9]:
df.describe()

Glucose  BloodPressure         BMI  DiabetesPedigreeFunction  \
count  573.000000     561.000000  570.000000                573.000000   
mean   120.753927      72.073084   32.414912                  0.484497   
std     31.772693      12.402765    7.028086                  0.339593   
min      0.000000       0.000000   18.200000                  0.078000   
25%     99.000000      64.000000   27.400000                  0.251000   
50%    117.000000      72.000000   32.000000                  0.389000   
75%    140.000000      80.000000   36.600000                  0.652000   
max    198.000000     122.000000   67.100000                  2.420000   

              Age     Outcome  
count  573.000000  573.000000  
mean    33.371728    0.345550  
std     11.919296    0.475963  
min     21.000000    0.000000  
25%     24.000000    0.000000  
50%     29.000000    0.000000  
75%     40.000000    1.000000  
max     81.000000    1.000000

Updating NaN values

In [10]:
BloodPressuremean=df["BloodPressure"].mean()

In [11]:
df=df.replace(np.nan,BloodPressuremean)
# Can also replace by fillna method or simple Imputer method

In [12]:
df["BloodPressure"].isnull().sum()

0

In [13]:
BMImean=df["BMI"].mean()

In [14]:
df=df.replace(np.nan,BMImean)

In [15]:
x=df.iloc[:,:-1].values #storing the attributes in variable x
y=df.iloc[:,-1].values  #storing the output(last column values) in variable y

Splitting of Data set into train test split

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)  #test size = 30% and train size = 70%
print(x_train)
print(x_test)

[[1.51e+02 9.00e+01 2.97e+01 2.94e-01 3.60e+01]
 [1.25e+02 6.00e+01 3.38e+01 8.80e-02 3.10e+01]
 [1.08e+02 7.00e+01 3.05e+01 9.55e-01 3.30e+01]
 ...
 [1.33e+02 8.80e+01 3.24e+01 2.62e-01 3.70e+01]
 [1.20e+02 7.40e+01 3.05e+01 2.85e-01 2.60e+01]
 [7.60e+01 6.20e+01 3.40e+01 3.91e-01 2.50e+01]]
[[1.07000000e+02 7.60000000e+01 4.53000000e+01 6.86000000e-01
  2.40000000e+01]
 [1.13000000e+02 4.40000000e+01 2.24000000e+01 1.40000000e-01
  2.20000000e+01]
 [1.08000000e+02 5.20000000e+01 3.25000000e+01 3.18000000e-01
  2.20000000e+01]
 [1.29000000e+02 6.40000000e+01 2.64000000e+01 2.19000000e-01
  2.80000000e+01]
 [9.50000000e+01 5.40000000e+01 2.61000000e+01 7.48000000e-01
  2.20000000e+01]
 [9.50000000e+01 6.00000000e+01 2.39000000e+01 2.60000000e-01
  2.20000000e+01]
 [1.48000000e+02 6.00000000e+01 3.09000000e+01 1.50000000e-01
  2.90000000e+01]
 [1.38000000e+02 7.60000000e+01 3.32000000e+01 4.20000000e-01
  3.50000000e+01]
 [8.10000000e+01 7.80000000e+01 4.67000000e+01 2.61000000e-01
  4.

Standardisation


In [17]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

Linear Regression Model


In [18]:
regressor=LinearRegression()

In [19]:
regressor.fit(x_train,y_train)
y_predict=regressor.predict(x_test)
print("Actual Test Values",y_test)
print("Predicted Values",y_predict)


Actual Test Values [0 0 0 1 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1
 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 1 0 0 0 1 0
 1 1 0 0 0 0 1 1 0 1 1 0 1 0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 1 0 1 0 1 1 0 0 0
 0 0 0 1 1 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 1 0 0 1 1 0]
Predicted Values [ 3.98170485e-01  9.05067436e-02  2.02894995e-01  2.62211564e-01
  9.95378855e-02  1.48110014e-03  4.35118268e-01  4.48531264e-01
  2.51425258e-01  2.71622155e-01  4.37080672e-01  5.74963737e-02
  2.05032682e-01  4.06884683e-01  3.05020814e-01  3.65021471e-01
  1.32889617e-01  1.03091272e-01  3.78751692e-02  6.05275818e-01
  5.96001819e-01  9.42970760e-02  2.69745702e-01  5.21987192e-01
  3.56084672e-01  2.31127357e-01  2.50986871e-01  5.77975985e-01
  2.51760830e-01  4.23957833e-02  3.72817362e-01  3.49599100e-02
  1.19657928e-01  2.57284333e-01  3.24536510e-01  2.97695146e-01
  1.70536347e-01 -7.89907224e

Slope and Intercept of Linear Regression Model

In [20]:
coefficient = regressor.coef_
intercept = regressor.intercept_
print('Coefficient', coefficient)
print('Intercept', intercept)

Coefficient [ 0.18108066 -0.00771913  0.10149083  0.04647057  0.04346576]
Intercept 0.33915211970074793


Performance Analysis of Linear Regression Model

In [21]:
R_square = r2_score(y_test, y_predict)
print('Coefficient of Determination', R_square)

Coefficient of Determination 0.23925310368394925


Prediction On Random Data

In [22]:
#Predicting the value on new data point
new_data_point = [[137,60,33.7,0.454,39]]
transformed_data_point = sc.transform(new_data_point)  #storing the new random data point in variable transformed_data_point
y_pred=regressor.predict(transformed_data_point)
print(y_pred)

[0.47590691]



K Nearest Neighbor Algorithm

In [23]:
k = 5
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(x_train, y_train)
y_predict = knn.predict(x_test)

Performance Analysis

In [24]:
accuracy = accuracy_score(y_test, y_predict)
print("Accuracy:", accuracy)
c_matrix=confusion_matrix(y_test, y_predict)
print("Confusion Matrix:")
print(c_matrix)

Accuracy: 0.7093023255813954
Confusion Matrix:
[[94 16]
 [34 28]]


Random test values

In [25]:
y_pre=knn.predict(transformed_data_point)
print(y_pre)

[0]
