In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('Student_Performance.csv')
dataset

Hours Studied  Previous Scores  Sleep Hours  \
0                7               99            9   
1                4               82            4   
2                8               51            7   
3                5               52            5   
4                7               75            8   
..             ...              ...          ...   
494              1               49            8   
495              7               67            7   
496              9               96            5   
497              4               45            6   
498              4               66            9   

     Sample Question Papers Practiced  Performance Index  
0                                   1                 91  
1                                   2                 65  
2                                   2                 45  
3                                   2                 36  
4                                   5                 66  
..                                ...                ...  
494                                 7                 26  
495                                 0                 57  
496                                 9                 91  
497                                 8                 29  
498                                 3                 48  

[499 rows x 5 columns]

In [ ]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
dataset.corr()

Hours Studied  Previous Scores  Sleep Hours  \
Hours Studied                          1.000000         0.061898    -0.052645   
Previous Scores                        0.061898         1.000000     0.041219   
Sleep Hours                           -0.052645         0.041219     1.000000   
Sample Question Papers Practiced      -0.015177         0.049052    -0.024891   
Performance Index                      0.428160         0.921935     0.055275   

                                  Sample Question Papers Practiced  \
Hours Studied                                            -0.015177   
Previous Scores                                           0.049052   
Sleep Hours                                              -0.024891   
Sample Question Papers Practiced                          1.000000   
Performance Index                                         0.066678   

                                  Performance Index  
Hours Studied                              0.428160  
Previous Scores                            0.921935  
Sleep Hours                                0.055275  
Sample Question Papers Practiced           0.066678  
Performance Index                          1.000000

In [ ]:
print(x, y)

[[ 7 99  9  1]
 [ 4 82  4  2]
 [ 8 51  7  2]
 ...
 [ 9 96  5  9]
 [ 4 45  6  8]
 [ 4 66  9  3]] [ 91  65  45  36  66  61  63  42  61  69  84  73  27  33  68  43  67  70
  30  63  71  85  73  57  35  49  66  83  74  74  39  36  58  47  60  74
  42  68  32  64  45  39  58  36  71  54  17  54  58  53  27  65  75  52
  78  91  33  47  78  38  70  98  87  49  41  71  54  42  91  61  74  54
  81  52  65  36  61  35  15  88  45  49  33  60  71  81  67  95  58  29
  21  38  60  76  69  30  57  81  36  25  27  61  34  76  57  45  76  83
  50  81  66  38  56  25  56  82  23  56  46  43  30  92  45  70  36  71
  49  82  71  43  77  86  34  49  69  84  41  68  44  41  58  68  94  47
  40 100  23  36  47  60  83  33  36  74  42  47  31  26  58  42  18  85
  36  58  45  60  56  42  33  77  51  72  57  53  16  45  49  67  49  73
  65  27  72  74  38  67  28  73  72  42  47  77  49  30  54  56  75  78
  32  89  29  57  48  27  38  18  66  65  27  33  37  29  26  72  77  45
  41  73  43  39  54  62  63

In [ ]:
ds = pd.read_csv('Social_Network_Ads.csv')
ds

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [ ]:
ds1 = pd.read_csv('iris.csv')
ds1

ds1 = ds1.fillna(ds1.mean())

# is data me label encoding pehle se hi kar rakhi hai

<ipython-input-24-d2f110cb08fc>:4: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  ds1 = ds1.fillna(ds1.mean())


In [ ]:
x = ds1.iloc[:, :-1].values
y = ds1.iloc[:, -1].values
print(x, y)

[[1.00000000e+00 5.10000000e+00 3.50000000e+00 1.40000000e+00
  2.00000000e-01]
 [2.00000000e+00 4.90000000e+00 3.00000000e+00 1.40000000e+00
  2.00000000e-01]
 [3.00000000e+00 4.70000000e+00 3.20000000e+00 1.30000000e+00
  2.00000000e-01]
 [4.00000000e+00 4.60000000e+00 3.10000000e+00 1.50000000e+00
  2.00000000e-01]
 [5.00000000e+00 5.00000000e+00 3.60000000e+00 1.40000000e+00
  2.00000000e-01]
 [6.00000000e+00 5.40000000e+00 3.90000000e+00 1.70000000e+00
  4.00000000e-01]
 [7.00000000e+00 4.60000000e+00 3.40000000e+00 1.40000000e+00
  3.00000000e-01]
 [8.00000000e+00 5.00000000e+00 3.40000000e+00 1.50000000e+00
  2.00000000e-01]
 [9.00000000e+00 4.40000000e+00 2.90000000e+00 1.40000000e+00
  2.00000000e-01]
 [1.00000000e+01 4.90000000e+00 3.10000000e+00 1.50000000e+00
  1.00000000e-01]
 [1.10000000e+01 5.40000000e+00 3.70000000e+00 1.50000000e+00
  2.00000000e-01]
 [1.20000000e+01 4.80000000e+00 3.40000000e+00 1.60000000e+00
  2.00000000e-01]
 [1.30000000e+01 4.80000000e+00 3.000000

In [ ]:
# Code for testing and training the data
from sklearn.model_selection import train_test_split

# Split data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [ ]:
# Code for precprocessing the dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-virginica' 'Iris-virgin

In [ ]:
new_data_point = [[0.0, 4, 3, 0.4]]
transformed_data_point = sc.transform(new_data_point)
predictions = classifier.predict(transformed_data_point)
print(predictions)

ValueError: X has 4 features, but StandardScaler is expecting 5 features as input.

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]


1.0