<a href="https://colab.research.google.com/github/Vaibhav-Chitransh/Machine-Learning-Files/blob/main/sklearn_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
list1 = [2,4,6, "name", True]
print(type(list1))
arr = np.array(list1)

print(arr)

<class 'list'>
['2' '4' '6' 'name' 'True']


In [ ]:
type(arr)
# nd array means this is n dimensional array

numpy.ndarray

In [ ]:
l1=[True,True,False]
l2 = [3, 67, 12]
l3 = ["Vaibhav", "Chitransh", "name"]

#Converting multiple lists to arrays
a = [l1,l2, l3]
b = np.array(a)

print(a)
type(l1)
type(b)


[[True, True, False], [3, 67, 12], ['Vaibhav', 'Chitransh', 'name']]


numpy.ndarray

In [ ]:
print(len(b[1]))

3


In [ ]:
print(b[0][0])

True


In [ ]:
b.shape

(3, 3)

In [ ]:
np.shape(b)

(3, 3)

In [ ]:
 d= np.array([[1,2,3,4,5], [10,20,30,40,50], [100,200,300,400,500],[11,2,3,4,5], [110,20,30,40,50], [1100,200,300,400,500],[111,2,3,4,5], [1560,20,30,40,50], [76100,200,300,400,500]])

In [ ]:
print(d)
print(len(d))

[[    1     2     3     4     5]
 [   10    20    30    40    50]
 [  100   200   300   400   500]
 [   11     2     3     4     5]
 [  110    20    30    40    50]
 [ 1100   200   300   400   500]
 [  111     2     3     4     5]
 [ 1560    20    30    40    50]
 [76100   200   300   400   500]]
5


In [ ]:
i = 0
while(i <= 1):
  j = 3
  while(j <= 4):
    print(d[i][j], end=" ")
    j = j+1
  i = i + 1
  print(end = '\n')

4 5 
40 50 


In [ ]:
d[0:8:2,3:5]
#Step can also be used by using colon in between

array([[  4,   5],
       [400, 500],
       [ 40,  50],
       [  4,   5]])

In [ ]:
arr1 = [1,2,3,4,5,6,7,8,9,0]
arr2 = np.array(arr1)
arr2.reshape(2,5)  #Reshaping the array by using reshape

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [ ]:
import pandas as pd

In [ ]:
lst = ["Hello", "Vaibhav", "Chitransh"]
myVar = pd.Series(lst)
print(myVar)
print(type(myVar))

0        Hello
1      Vaibhav
2    Chitransh
dtype: object
<class 'pandas.core.series.Series'>


In [ ]:
#INITIALISE DATA
data={'Name':['Tim','jim','kim','Krish'],'Age':[20,18,19,18]}
data


{'Name': ['Tim', 'jim', 'kim', 'Krish'], 'Age': [20, 18, 19, 18]}

In [ ]:
df=pd.DataFrame(data)
df

Name  Age
0    Tim   20
1    jim   18
2    kim   19
3  Krish   18

In [ ]:
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Vishal'],
        'Age':[27, 47, 23 , 63],
        'Percentage':[99, 87, 85,76],
        'Address':['Lucknow', 'Kanpur', 'Allahabad', 'Kannauj']}

In [ ]:
df2=pd.DataFrame(data1)
df2

Name  Age  Percentage    Address
0     Jai   27          99    Lucknow
1  Princi   47          87     Kanpur
2  Gaurav   23          85  Allahabad
3  Vishal   63          76    Kannauj

In [ ]:
row2=df2.iloc[1:2,1::]
print(type(row2))
print(row2)


<class 'pandas.core.frame.DataFrame'>
   Age  Percentage Address
1   47          87  Kanpur


In [ ]:
row3=df2.loc[0:3,'Age']
print(type(row3))
print(row3)

<class 'pandas.core.series.Series'>
0    27
1    47
2    23
3    63
Name: Age, dtype: int64


In [ ]:
data2 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27,'Nill', 23 , np.nan],
        'Percentage':[np.nan, 87, 85,76],
        'Address':['Lucknow', 'Kanpur', 'Allahabad', 'Kannauj']}
df3=pd.DataFrame(data2)
df3


Name   Age  Percentage    Address
0     Jai    27         NaN    Lucknow
1  Princi  Nill        87.0     Kanpur
2  Gaurav    23        85.0  Allahabad
3    Anuj   NaN        76.0    Kannauj

In [ ]:
df3['Percentage'].isnull().sum()

1

In [ ]:
df3.describe()

Percentage
count    3.000000
mean    82.666667
std      5.859465
min     76.000000
25%     80.500000
50%     85.000000
75%     86.000000
max     87.000000

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Name        4 non-null      object 
 1   Age         3 non-null      object 
 2   Percentage  3 non-null      float64
 3   Address     4 non-null      object 
dtypes: float64(1), object(3)
memory usage: 256.0+ bytes


In [ ]:
df3=df3.replace('Nill',np.NaN)
inputrows=df3[df3['Age'].isnull()]
inputrows

Name  Age  Percentage  Address
1  Princi  NaN        87.0   Kanpur
3    Anuj  NaN        76.0  Kannauj

In [ ]:
Age_mean=np.mean(df3['Age'])
Age_mean


25.0

In [ ]:
inputrows2=inputrows.replace(np.NaN,Age_mean)
inputrows2

Name   Age  Percentage  Address
1  Princi  25.0        87.0   Kanpur
3    Anuj  25.0        76.0  Kannauj

In [ ]:
data2 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27,np.nan, 23 , np.nan],
        'Percentage':[np.nan, 87, 85,76],
        'Address':['Lucknow', 'Kanpur', 'Allahabad', 'Kannauj']}
df3=pd.DataFrame(data2)
df3

Name   Age  Percentage    Address
0     Jai  27.0         NaN    Lucknow
1  Princi   NaN        87.0     Kanpur
2  Gaurav  23.0        85.0  Allahabad
3    Anuj   NaN        76.0    Kannauj

In [ ]:
df3

Name   Age  Percentage    Address
0     Jai  27.0   82.666667    Lucknow
1  Princi  25.0   87.000000     Kanpur
2  Gaurav  23.0   85.000000  Allahabad
3    Anuj  25.0   76.000000    Kannauj

In [ ]:
df3.fillna(df3.mean(), inplace = True);
print(df3)

     Name   Age  Percentage    Address
0     Jai  27.0   82.666667    Lucknow
1  Princi  25.0   87.000000     Kanpur
2  Gaurav  23.0   85.000000  Allahabad
3    Anuj  25.0   76.000000    Kannauj


<ipython-input-108-b1d7bde60d4b>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df3.fillna(df3.mean(), inplace = True);


In [ ]:
data_1 = {'Name':['Vaibhav' , 'Rishi', 'Gagan', 'Anshu'],
          'Age' : [20, 21, 21, np.nan],
          'Occupation': ['MERN Stack Developer', 'Programmer', 'Android Developer', 'UI/UX Designer'],
          'HomeTown': ['Jaipur', 'Chennai', 'Varanasi', 'Gwalior'],
          'NetWorth' : ['120 billion', '100 billion', '390 million', '80 billion']}

dataset1 = pd.DataFrame(data_1)
dataset1

Name   Age            Occupation  HomeTown     NetWorth
0  Vaibhav  20.0  MERN Stack Developer    Jaipur  120 billion
1    Rishi  21.0            Programmer   Chennai  100 billion
2    Gagan  21.0     Android Developer  Varanasi  390 million
3    Anshu   NaN        UI/UX Designer   Gwalior   80 billion

In [ ]:
occupation_col = dataset1.loc[0:3, 'Occupation']
print(occupation_col)

0    MERN Stack Developer
1              Programmer
2       Android Developer
3          UI/UX Designer
Name: Occupation, dtype: object


In [ ]:
dataset1.shape

(4, 5)

In [ ]:
np.shape(dataset1)

(4, 5)

In [ ]:
dataset1.fillna(dataset1.mean(), inplace = True)

<ipython-input-113-b8266b4b5f9f>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dataset1.fillna(dataset1.mean(), inplace = True)


In [ ]:
print(dataset1)

      Name        Age            Occupation  HomeTown     NetWorth
0  Vaibhav  20.000000  MERN Stack Developer    Jaipur  120 billion
1    Rishi  21.000000            Programmer   Chennai  100 billion
2    Gagan  21.000000     Android Developer  Varanasi  390 million
3    Anshu  20.666667        UI/UX Designer   Gwalior   80 billion


In [ ]:
dataset_array = dataset1.iloc[:,:].values
print(type(dataset_array))
print(dataset_array)


<class 'numpy.ndarray'>
[['Vaibhav' 20.0 'MERN Stack Developer' 'Jaipur' '120 billion']
 ['Rishi' 21.0 'Programmer' 'Chennai' '100 billion']
 ['Gagan' 21.0 'Android Developer' 'Varanasi' '390 million']
 ['Anshu' 20.666666666666668 'UI/UX Designer' 'Gwalior' '80 billion']]


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
imputer.fit(dataset_array[:, 1:3])
dataset_array[:, 1:3] = imputer.transform(dataset_array[:, :])

ValueError: Cannot use mean strategy with non-numeric data:
could not convert string to float: 'MERN Stack Developer'

In [ ]:
data_1 = {'Name':['Vaibhav' , 'Rishi', 'Gagan', 'Anshu'],
          'Age' : [20, 21, 21, np.nan],
          'Occupation': ['MERN Stack Developer', 'Programmer', 'Android Developer', 'UI/UX Designer'],
          'HomeTown': ['Jaipur', 'Chennai', 'Varanasi', 'Gwalior'],
          'NetWorth' : ['120 billion', '100 billion', '390 million', '80 billion']}

dataset1 = pd.DataFrame(data_1)
dataset1

Name   Age            Occupation  HomeTown     NetWorth
0  Vaibhav  20.0  MERN Stack Developer    Jaipur  120 billion
1    Rishi  21.0            Programmer   Chennai  100 billion
2    Gagan  21.0     Android Developer  Varanasi  390 million
3    Anshu   NaN        UI/UX Designer   Gwalior   80 billion

In [ ]:
dataset_array = dataset1.iloc[:,:].values
print(type(dataset_array))
print(dataset_array)

<class 'numpy.ndarray'>
[['Vaibhav' 20.0 'MERN Stack Developer' 'Jaipur' '120 billion']
 ['Rishi' 21.0 'Programmer' 'Chennai' '100 billion']
 ['Gagan' 21.0 'Android Developer' 'Varanasi' '390 million']
 ['Anshu' nan 'UI/UX Designer' 'Gwalior' '80 billion']]


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
imputer.fit(dataset_array[:, 1:2])
dataset_array[:, 1:2] = imputer.transform(dataset_array[:, 1:2])

In [ ]:
print(dataset_array)

[['Vaibhav' 20.0 'MERN Stack Developer' 'Jaipur' '120 billion']
 ['Rishi' 21.0 'Programmer' 'Chennai' '100 billion']
 ['Gagan' 21.0 'Android Developer' 'Varanasi' '390 million']
 ['Anshu' 20.666666666666668 'UI/UX Designer' 'Gwalior' '80 billion']]


In [ ]:
import pandas as pd


In [ ]:
dataframeNew = pd.read_csv('/content/sample_data/california_housing_test.csv')
dataframeNew

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

In [ ]:
x1 = dataframeNew.iloc[:, 1:3]
y1 = dataframeNew.iloc[:, -1]

In [ ]:
print(x1)
print("\n")
print(y1)

      latitude  housing_median_age
0        37.37                27.0
1        34.26                43.0
2        33.78                27.0
3        33.82                28.0
4        36.33                19.0
...        ...                 ...
2995     34.42                23.0
2996     34.06                27.0
2997     36.30                10.0
2998     34.10                40.0
2999     34.42                42.0

[3000 rows x 2 columns]


0       344700.0
1       176500.0
2       270500.0
3       330000.0
4        81700.0
          ...   
2995    225000.0
2996    237200.0
2997     62000.0
2998    162500.0
2999    500001.0
Name: median_house_value, Length: 3000, dtype: float64


In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaling = MinMaxScaler()
scaling.fit_transform(x1)

array([[0.51388889, 0.50980392],
       [0.18162393, 0.82352941],
       [0.13034188, 0.50980392],
       ...,
       [0.39957265, 0.17647059],
       [0.16452991, 0.76470588],
       [0.19871795, 0.80392157]])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaling = StandardScaler()
scaling.fit_transform(x1)

array([[ 0.81463305, -0.14699983],
       [-0.64593087,  1.12756514],
       [-0.87135553, -0.14699983],
       ...,
       [ 0.31212392, -1.5012251 ],
       [-0.72107242,  0.88858421],
       [-0.57078932,  1.04790483]])

In [ ]:
from sklearn import preprocessing
sc = preprocessing.StandardScaler()
z = sc.fit_transform(x1)

In [ ]:
print(z)

[[ 0.81463305 -0.14699983]
 [-0.64593087  1.12756514]
 [-0.87135553 -0.14699983]
 ...
 [ 0.31212392 -1.5012251 ]
 [-0.72107242  0.88858421]
 [-0.57078932  1.04790483]]


In [ ]:
testDataframe = pd.read_csv('/content/sample_data/mnist_test.csv')
print(testDataframe)
testDataframe.shape


      7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665

<bound method NDFrame.head of       7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0         0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...  
9994      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0  

[9999 rows x 785 columns]>

In [ ]:
testDataframe.head()

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [ ]:
testDataframe.tail()

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  
9994      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [ ]:
testDataset_array = testDataframe.iloc[:,:].values
print(testDataset_array)

[[2 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [4 0 0 ... 0 0 0]
 [5 0 0 ... 0 0 0]
 [6 0 0 ... 0 0 0]]


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
imputer.fit(testDataset_array[:, 0:4])
testDataset_array[:, 0:4] = imputer.transform(testDataset_array[:, 0:4])

In [ ]:
print(testDataset_array)

[[2 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [4 0 0 ... 0 0 0]
 [5 0 0 ... 0 0 0]
 [6 0 0 ... 0 0 0]]


In [ ]:
test1 = pd.DataFrame(testDataset_array)
print(test1)

In [ ]:
test = test1.iloc[:, 1:4].values

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaling = MinMaxScaler()
ft=scaling.fit_transform(test)
print(ft)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
from sklearn import preprocessing
sc = preprocessing.StandardScaler()
testData = sc.fit_transform(test)

In [ ]:
print(testData)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(test1)